In [1]:
import pandas as pd

In [2]:
def get_data_set(file_name: str, indicator_name: str):
    data = pd.read_csv(file_name, header = 2)
    data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
    data = data[(data['Indicator Name'] == indicator_name)]
    data = data.drop(columns=['Indicator Name', 'Indicator Code'])
    data = data.set_index('Country Code')
    return data

In [3]:
get_data_set("data/trade.csv", 'Travel services (% of commercial service exports)')

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.277930,85.907219,86.082926,86.502936,86.375526,86.538972,87.382643,81.195601,86.924168,87.864724
AFE,Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59.074492,58.913765,58.034131,57.414302,57.167153,59.044167,60.209970,31.897101,29.885968,37.420524
AFG,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.477215,8.494798,10.187853,11.050082,0.512371,4.497357,14.367959,10.803949,NaN,NaN
AFW,Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.831742,32.672191,18.831927,31.877371,45.398076,37.669790,29.193098,12.123303,15.879071,NaN
AGO,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.768785,94.509425,92.560769,87.610526,89.419479,86.184631,84.482965,24.195671,23.816580,23.916647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XKX,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,77.413526,74.561227,78.535093,82.399305,84.215734,80.490437,80.415185,65.391498,79.530390,75.588472
YEM,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.591070,68.091875,38.108976,32.398573,NaN,NaN,NaN,NaN,NaN,NaN
ZAF,South Africa,64.571429,65.555556,63.297872,63.207547,61.751152,61.403509,61.132075,58.862876,57.186544,...,55.339493,55.522886,54.450212,54.322887,54.600158,53.788485,53.943918,31.030943,23.752829,38.264025
ZMB,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72.756503,75.398695,76.626541,77.120072,75.444767,77.862845,80.965044,74.070918,74.779380,88.241141
ZWE,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.274662,51.746950,51.302909,50.855094,34.770504,40.309499,50.326041,19.982796,NaN,NaN